### ISSUE TITLE
Plant status turns OK when device is unavailable

### ISSUE THREAD

**Issue by xanox1** [Olen/homeassistant-plant#105]
Not sure if this is by design, but it throws off some of my automations and notifications. 
Would it be possible to differentiate between unavailable and ok?

**Comment by xanox1** [comment]
![image](https://github.com/Olen/homeassistant-plant/assets/43671644/20b45f9a-8336-4bc5-b93f-0d123df078a6)

**Comment by Olen** [comment]
I am not sure exactly what is the best thing to do here.
I don't think it is right to set the plant state to unavailable if only ONE of the sensors become unavailable (Humidiaty in your case).
But maybe if they all are unavailable, the plant itself should be unavailable too?

And I am not sure it is better to set the state to "Problem" if one of the sensors are unavailble, but maybe that is better than setting it as "ok"...

**Comment by xanox1** [comment]
Hi Olen,

The humidity status is always unknown, it's not set as a problem trigger. 

The problem is that sometimes the device drops the connection and it registers as unavailable within home assistant, at that point the plant sensor always seems to report OK, while the plant itself, in this case, is in problem state due to the conductivity status being low and it's set as a problem trigger. 

I would love to have it just keep the current status until the device is available again. Perhaps with an added property that tells if the device is on or offline. 

Just some thoughts.

**Comment by MrMxyzptlk** [comment]
I have a similar issue but different needs. I have 6 plants on some Xiomi sensors and they show problem constantly except for every hour when they send out updates; this means they are working properly, and I do NOT want to see 'problem' or 'offline'. I would prefer to see something like, last update 36 minutes, or ability to set how often a particular sensor updates and then have your integration update it's status based on that. Let me know if that made any sense.

**Comment by Olen** [comment]
What does your xiaomi devices show when this happens?
The plant sensors are just copying the state from the xiaomi sensors, so as long as the xiaomi sensors have a value, the plant sensor should have the same value.

## Example

### Xiamio

![image](https://github.com/Olen/homeassistant-plant/assets/203184/478b3ca9-56c4-484f-b37a-1a46ccc879a8)

### Plant

![image](https://github.com/Olen/homeassistant-plant/assets/203184/a59d0060-6f4d-4557-837e-9884fab2c766)

**Comment by MrMxyzptlk** [comment]
They appear fine; for example.

<img width="1057" alt="Screenshot 2023-11-07 at 7 28 43 AM" src="https://github.com/Olen/homeassistant-plant/assets/1753001/a0eb3203-5f20-43d2-92eb-8c607bde22f5">

**Comment by MrMxyzptlk** [comment]
<img width="586" alt="Screenshot 2023-11-07 at 7 33 10 AM" src="https://github.com/Olen/homeassistant-plant/assets/1753001/23409901-aac9-4000-ae3c-2dbfd8860ede">

**Comment by MrMxyzptlk** [comment]
<img width="507" alt="Screenshot 2023-11-07 at 7 33 18 AM" src="https://github.com/Olen/homeassistant-plant/assets/1753001/534a879a-5644-4db7-8675-38e6f981af91">

**Comment by Olen** [comment]
I can't see anything here that looks wrong? 
You have all the values in your plant, what is not working?

**Comment by MrMxyzptlk** [comment]
It says there is a 'problem'; there is not, it just isn't sending out status updates at the moment.

**Comment by Olen** [comment]
On your screenshots both light and dli are below the limits, hence you have a problem.
You can disable the problem triggers in the Integration configuration.

**Comment by MrMxyzptlk** [comment]
OK, I will give that a try; thank you.

**Comment by ChristophCaina** [comment]
Hi :)
I just have the same issue right now.

The integration was working well - yes, the integration is reporting a "problem" continuesly, but right now - I am fine with it.
Now, the battery just died and all values went "unknown"... which caused the integration to switch to OK

the thing is:
The card will also disappear when the sensors become unavailable...
I just noticed this, because only the information for signal strenght was visible on my dashboard (might be an issue for the card)

![image](https://github.com/Olen/homeassistant-plant/assets/26391061/9076430e-e840-486d-b4df-cd976f6099d0)

![image](https://github.com/Olen/homeassistant-plant/assets/26391061/5b60d03e-6f67-4062-938e-8de7ce9873c5)

![image](https://github.com/Olen/homeassistant-plant/assets/26391061/e9a9a760-570b-4731-afa0-98ff1816c910)

**Comment by Olen** [comment]
This is completely unrelated.
I am not sure what the issue you are seeing is, but it has nothing to do with "problem" or "ok"

**Comment by ChristophCaina** [comment]
Hi,
The issue I am facing seems to be related with the check for "OK" or "Problem" status  in the case, that ALL sensor values become unknown.

For me, it looks like the check for "OK" will be passed, when all monitored entities do not report the 'expected' value and therefore, the integration cannot check against the threasholds.

That the card isn't visible in this case has been reported in the git for the card itself.

**Comment by Olen** [comment]
> The issue I am facing seems to be related with the check for "OK" or "Problem" status in the case, that ALL sensor values become unknown.

Yes.  This is correct.  The "default" is "OK"
https://github.com/Olen/homeassistant-plant/blob/157263c950744e90895df8b1fc0986f61ad5401c/custom_components/plant/__init__.py#L628

I don't really want the default state to be "Problem" as that seems wrong.  But one could maybe add a check and say that if all sensors are Unknown, then let the plant  state be unknown to.

**Comment by Olen** [comment]
See #128
