### ISSUE TITLE
Integration fails to load on 2023.11

### ISSUE THREAD

**Issue by NickM-27** [Olen/homeassistant-plant#106]
Seeing this error

`Unable to prepare setup for platform plant.number: Platform not found (No module named 'homeassistant.util.temperature').`

will look to see if I can find the commit that made the change

**Comment by NickM-27** [comment]
looks like the temperature conversion functions were deprecated https://github.com/home-assistant/core/commit/8626a4888c735d66f85cb78b6dfe042c2061065c

**Comment by jpbede** [comment]
Yes, they're deprecated and have been removed: https://developers.home-assistant.io/blog/2023/10/03/conversion-functions-cleanup

**Comment by Olen** [comment]
Thanks!

**Comment by didekoning** [comment]
This is still an issue since it is also used in plant_tresholds.py. Have created a new pr https://github.com/Olen/homeassistant-plant/pull/112 to fix this.
