### ISSUE TITLE
HACS compatibility

### ISSUE THREAD

**Issue by robertalexa** [Olen/homeassistant-plant#11]
Hi @Olen 

Just a very quick one, I know you mentioned earlier that you have lacked time recently.

I was looking over this recently (custom component and plant card) as I have forgotten how I have added them and what the update process is. And I have discovered that there isn't really one :)

I have added the Plant card as a custom repository via HACS, but the custom component doesn't work, as the repo does not use the required format.

Was wondering if you intend to have a look at this at some point.

By the looks of it, you will need a hacs.json file with very little info in it, and (probably the best approach) to move the module files into a subfolder. All information can be found here https://hacs.xyz/docs/publish/integration

Let me know your thought on this, it might be that i might have some time in the near future and could try to fork it and do it myself, then submit a PR.

Thanks in advance

**Comment by Albuca** [comment]
Until it is integrated, you can manually add this repository as a custom repository to HACS for installation and updates.

See this excellent post on how to go about this method: https://github.com/dolezsa/thermal_comfort/issues/18#issuecomment-922367967

**Comment by robertalexa** [comment]
@Albuca I am aware how to do it, but that is not working. That is because the repository does not use the required format. As mentioned in my original post.

![image](https://user-images.githubusercontent.com/9019306/135510802-d4ef2454-fba5-4822-add9-3166afdacfe0.png)

**Comment by Albuca** [comment]
@robertalexa -- you are correct!  Sorry, read through your initial post a bit too quickly it seems.

**Comment by Olen** [comment]
Thanks for the fix.
