### ISSUE TITLE
Plant cards stopped loading after a recent update 

### ISSUE THREAD

**Issue by paulwakeford** [Olen/homeassistant-plant#111]
Started with a recent update to HA - sorry I can’t identify which one. 

Log Details (ERROR)

Logger: homeassistant.setup
Source: setup.py:359
First occurred: 14:20:30 (10 occurrences)
Last logged: 14:20:30

Unable to prepare setup for platform plant.number: Platform not found (No module named 'homeassistant.util.temperature').

I saw that ‘homeassistant.util.temperature' is deprecated?

**Comment by paulwakeford** [comment]
This is the other ref I found 

https://github.com/Limych/ha-iaquk/issues/126

**Comment by Olen** [comment]
This should have been fixed with the latest version

**Comment by paulwakeford** [comment]
It is - thanks. Am I missing a notification system for updates to HACS installed integrations? (Good to close this ticket thanks).

**Comment by Olen** [comment]
There is no built in notifications for updates as far as I know, however, there is a sensor (sensor.hacs) that will list available updates, and can trigger any kind of notification.
