### ISSUE TITLE
Soil moisture showing value from battery instead of moisture

### ISSUE THREAD

**Issue by tr4nt0r** [Olen/homeassistant-plant#119]
I had the problem that Soil moisture was showing showing the sensor value of the battery instead of the moisture. When clicking on Attributes it showed under External sensor that it was linked to the battery entity of my Xiaomi flowercare. I deleted and recreated the Plant several times because i thought maybe i linked the wrong external sensor entity, but the problem persisted.

I think this may be the same problem as described here:

https://github.com/Olen/homeassistant-plant/issues/104

I had set the name of the plant to `Nephrolepis exaltata 'Bostoniensis'`, after changing it to `Boston Fern` it now shows the correct sensor value and in the attributes it also shows correctly that it is taking the value from the correct external sensor.

The version of homeassistant-plant i have installed is v2023.11.0

**Comment by Olen** [comment]
HA is quite good at preserving metadata about sensors of you remove and re-add a device, so I guess that is your problem.
Just use the service call to change the source sensor for your moisture sensor:
https://github.com/Olen/homeassistant-plant?tab=readme-ov-file#easier-to-replace-sensors

**Comment by tr4nt0r** [comment]
tried to reproduce this with a new plant but all worked just fine, could not reproduce this error. Still wondering how this happened as you can't wrongfully select a battery sensor instead of a moisture sensor, the selector dropdown only shows humidity entities. 🤷‍♂️
