### ISSUE TITLE
missing timezone information Error since 2021.12

### ISSUE THREAD

**Issue by felix63** [Olen/homeassistant-plant#13]
`Exception in message_received when handling msg on 'sensor/plants/plant1/': '{"battery": 67, "temperature": "18.1", "brightness": 195, "moisture": 21, "conductivity": 171, "timestamp": "2021-12-16T00:30:05.497001"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.plant1_timestamp provides state '2021-12-16 00:30:05.497001', which is missing timezone information`

**Comment by Olen** [comment]
Are you sure the error comes from this component?  I see references there to mqtt.  Also, this component does not have any "timestamp" attributes or sensors.

**Comment by felix63** [comment]
You are right, it's in MQTT. I fixed it by tweaking the  plantgateway to modify the way the MQTT message was composed. Sorry for troubling you!
