### ISSUE TITLE
Illuminance data not retrieved from the related sensor

### ISSUE THREAD

**Issue by sipossz** [Olen/homeassistant-plant#131]
This is the flower card and the original sensor data from dashboard. As it can be seen, the illuminance data not retrieved from the related senor (double checked), all other sensor implementation is fine.
![image](https://github.com/Olen/homeassistant-plant/assets/78107707/5e93b491-1b3e-4e6c-9d31-470ac3daed90)

**Comment by Olen** [comment]
Try the "replace sensor" service call to re-add the illuminance sensor

**Comment by Olen** [comment]
Also, check the attributes of the sensor in the plant-device.  It should show the entity_id of the original sensor

**Comment by sipossz** [comment]
The replace sansor helped, now it works well. Orignally I added more times the plant device, but I always get the same result with the illuminance entity.
Thanks!
