### ISSUE TITLE
Change humidity sensor source after creation.

### ISSUE THREAD

**Issue by SirSheik** [Olen/homeassistant-plant#143]
Hello.
First of all congratulations for this excellent complement. It is very useful and I thank you for the time you dedicate to its development.
I would like to know if it is possible to change the origin of the humidity sensor once it has been declared, this is because I have plants that initially had an indoor humidity sensor, but now that the weather is starting to be good, I have taken them outside.
I have tried unsuccessfully to edit the device definition directly in the file :
/root/config/.storage/core.config_entries
![Image 406](https://github.com/Olen/homeassistant-plant/assets/31892065/c843cae6-46ba-4bc0-9d5d-3e01218b4431)

But despite reboot it does not take correctly the change.
![Image 407](https://github.com/Olen/homeassistant-plant/assets/31892065/d126bb83-b70a-42cc-a544-4160664bc6ac)

Even deleting the entity and re-creating it does not respect the new sensor that I indicate and continues to take the old sensor.
Can you think of a way to change it without having to create a new device?
Thank you very much

**Comment by Olen** [comment]
Please see the readme. Especially the section about replacing sensors.

**Comment by SirSheik** [comment]
Thank you very much. It worked perfectly.
My apologies I did not know about the existence of this service to change the reference sensors. 🤦🏻‍♂️
I close this.
Have a nice day

**Comment by SirSheik** [comment]
Resolved with
https://github.com/Olen/homeassistant-plant#easier-to-replace-sensors
