### ISSUE TITLE
ghost entitiesHi Olen, in my case when I delete a plant there are ghost entities that I can't delete. Any help? 

### ISSUE THREAD

**Issue by Waterbrain** [Olen/homeassistant-plant#144]
Hi Olen, in my case when I delete a plant there are ghost entities that I can't delete. Any help?

![Captura de Pantalla 2024-02-28 a las 9 13 34](https://github.com/Olen/homeassistant-plant/assets/5563436/b3a52ce3-a30e-449c-8b8f-9117cff3ada1)

**Comment by Olen** [comment]
These should disappear after a HA restart

**Comment by Waterbrain** [comment]
I have already done it but it is still the same. I'm going to do one with restarting the raspberry.

**Comment by Waterbrain** [comment]
![Captura de Pantalla 2024-02-28 a las 9 33 14](https://github.com/Olen/homeassistant-plant/assets/5563436/5b69cdb2-ab1d-460f-bd24-08c272b1e05a)

I'm sorry but I'm still the same

**Comment by Olen** [comment]
Without any more information, it is very hard to help.

Please search your logs and see if you can find anything there.

**Comment by Waterbrain** [comment]
I had also forgotten that the icon mdi:counter was missing from the card. 
![Captura de Pantalla 2024-02-28 a las 9 48 15](https://github.com/Olen/homeassistant-plant/assets/5563436/525ab7dc-5164-460f-b966-6ec3ddb1b0df)
This has worked.
[home-assistant_2024-02-28T08-53-12.577Z.log](https://github.com/Olen/homeassistant-plant/files/14431199/home-assistant_2024-02-28T08-53-12.577Z.log)

**Comment by Olen** [comment]
DLI icon was added recently.  Disapeeared for some reason at some point.  Added back now.

The other issue is resolved by removing the manual config, I believe.
