### ISSUE TITLE
Odd sensor bahaviour. 

### ISSUE THREAD

**Issue by jonnybergdahl** [Olen/homeassistant-plant#146]
I have one plant that seems to use the wrong moisture sensor. I checked the `core.config_entries` and it shows the correct sensor (the `_d` one) being used.

```
        "title": "Rosmarin GCKN",
        "data": {
          "plant_info": {
            "name": "Rosmarin GCKN",
            "species": "rosmarinus officinalis",
            "temperature_sensor": "sensor.growcube_c13acc_temperature",
            "moisture_sensor": "sensor.growcube_c13acc_moisture_d",
```

However, the `sensor.rosmarin_gckn_soil_moisture` sensor shows these attributes, saying it uses the (faulty) `_a` one?

```state_class: measurement
external_sensor: sensor.growcube_c13acc_moisture_a
unit_of_measurement: "%"
device_class: moisture
icon: mdi:water
friendly_name: Rosmarin GCKN soil moisture```

Not sure how to even troubleshoot this.

I have deleted this plant, restarted, and re-added 3 times, and the result was the same every time.

**Comment by Olen** [comment]
Try the replace_sensor service call (see the readme) and check if that helps.

**Comment by jonnybergdahl** [comment]
Thanks, that did the job. Not sure how this could happen though, is HA secretly caching entities, even to the point of surviving a restart?

**Comment by Olen** [comment]
HA is _extremely_ good at preserving stuff even through deleting an entity and creating a new with the same name/entity_id.
