### ISSUE TITLE
Issues comparing sensor values in Fahrenheit with min/max values in Celsius

### ISSUE THREAD

**Issue by williamahartman** [Olen/homeassistant-plant#15]
I have my Home Assistant instance set to use Fahrenheit, so the values on my sensors come back in °F. The values in the attributes on the plant entity also come through in °F, as expected. However, it look like the min/max values on OpenPlantbook are all in Celsius and aren't converted before they are compared with the Fahrenheit values, so it reports a "problem" when it shouldn't.

![image](https://user-images.githubusercontent.com/7718837/147841382-2f1a8f61-dd91-4b36-ae01-9c6879557d77.png)

This is pretty easy to work around by just setting min/max values in °F in the config yaml, but it could be a little cleaner if it worked automatically.

**Comment by tomofdarkness** [comment]
I would also appreciate a way to override this for all plantbook entries instead of looking up values and converting them manually for each plant.

**Comment by Olen** [comment]
In the upcoming version, all values are easily overridden.

https://github.com/Olen/homeassistant-plant/tree/new_plant

However I have not looked into auto conversion between C and F.
I'll get back to it.

**Comment by Olen** [comment]
The new version now supports converting between C and F:

![image](https://user-images.githubusercontent.com/203184/181259328-f5d386bf-3dce-4ed2-b683-882f2d4b0c66.png)

![image](https://user-images.githubusercontent.com/203184/181259071-58622446-3e24-4f93-8334-293748958bd2.png)

It depends on the sensors temperature unit and what you have set HA to show.  But there are many ptifalls here, so it might be corener cases where it does not work correctly...

**Comment by Olen** [comment]
Closing this as it is fixed in the upcoming version.
