### ISSUE TITLE
only moisture and conductivity recognize helper entities

### ISSUE THREAD

**Issue by silelmot** [Olen/homeassistant-plant#156]
Hi,
when adding a new plant and i am pointing on temperature, i get a dropdown with all my sensors. but my sensor created from helpers isn't shown. when adding it by name i get an error , adding it by the long name "sensor.esp_blablablab" i can add it somehow.
same with illuminance. 
conductivity and moisture are working as expected.

**Comment by Olen** [comment]
The dropdowns only lists sensors with the correct DeviceClass.
If you use template sensors, you need to add the correct DeviceClass to them to be listed in the dropdowns.

**Comment by silelmot** [comment]
Shouldnt be a problem of device lass. I can select them without problems in the conductivity or moisture-dropdown. I cant select any of the helpers which work in con and hum. All 4 dropdowns should work the same. 
Helper is just to get latest input about a plant from 3 esp32-satellites.

**Comment by Olen** [comment]
Conductivity dropdown does not have a requirement for a device class, as there is no device class defined for this kind of sensors. 
The Moisture device class was recently defined, so in a later release, I will add the requirement to this sensor dropdown as well.  The point is to limit the number of entries in the dropdown to make it easier to select the right one.

Just add the correct device class to your custom sensors, and they will show up.

**Comment by DNier** [comment]
I want to reopen this issue, because I have a related issue:

I use the GARDENA smart Sensor from Gardena. The Soil humidity from those sensors doesn't show up in the setup dropdown:

![image](https://github.com/Olen/homeassistant-plant/assets/12126535/0b69a11a-4b26-4125-b2b0-4a87f4cee6a9)
