### ISSUE TITLE
Assign tasks for plants and make a note when completed

### ISSUE THREAD

**Issue by mikburnz** [Olen/homeassistant-plant#157]
It would be great if regularly recurring tasks such as fertilizing and pruning could be stored in the database with calendar weeks. Upon completion of the task, confirmation is provided. The task will recur at the next scheduled time.

**Comment by Olen** [comment]
Sounds like a regular "recurring task" that is supported by [some  calendars](https://support.google.com/calendar/answer/12132599?hl=en&co=GENIE.Platform%3DAndroid). 
As I don't think it is supported in HA-calendars currently, this is needs to be added to the calendar integration first.

Feel free to create a PR for a calendar-integration and then to this integration once that is implemented.

**Comment by mikburnz** [comment]
Tried PR first but it wasn’t possible. Calendar is a possibility. I love the idea to see the task directly in the Lovelace card dedicated to the plant close to the other informations. Added value is huge imho

**Comment by Olen** [comment]
I think this is easier to do with the already existing features of HA.
Add a todo-list or a calendar for your tasks, and create a few buttons or automations to add new tasks or complete them when done.
Then use any entities-card, todolist-card, calendar-card or whatnot to display them.
We can't implement every single thing that HA already do quite well in this integration.
