### ISSUE TITLE
No check_days implementation?

### ISSUE THREAD

**Issue by simonince** [Olen/homeassistant-plant#16]
Hey, I'm getting the light intensity warning at all times... I think the original plant implementation uses check_days to build an average (although I'm not completely sure that's how it works). Is there a way to get that working with this version, rather than just turning off light warnings altogether? Thx

**Comment by slaxor505** [comment]
It's been fixed now by updating to the latest core-plant component in this PR https://github.com/Olen/homeassistant-plant/pull/25.
The original component just remembers the max brightness over "check_day" period and use it for min comparison. Which kind of makes sense but overly simplified. We actually need to calculate and compare against day light integral rather. I will work on how we can implement it in future.

**Comment by Olen** [comment]
It might be fixed by #25 , and the upcoming version will use a completely different logic to alert on light (e.g. DLI).

https://github.com/Olen/homeassistant-plant/tree/new_plant

Please test it out and report any issues you find.
