### ISSUE TITLE
only works with one and only Plant Detector

### ISSUE THREAD

**Issue by Malvu** [Olen/homeassistant-plant#161]
Good morning
very good addon if it worked correctly.
I use 5 HHCCJCY01 by Xiaomi via bluetooth, and the sensor information comes back without problem in Home assistant.
on the other hand, from the moment you use your addon only the information from the first sensor is available.
all the others are "unknown", so your work is totally unusable for me

**Comment by Olen** [comment]
I personally have 10 sensors and I know other users have many more. This integration only mirrors the data from the physical sensors, so there is no limit to how many plants and sensors you can add.

How do you expect me to troubleshoot this issue with so little information from you?

**Comment by Malvu** [comment]
for the same sensor see photograph

Flower Card - v2024.4.1
And
Alternative plants component for Home Assistant - v2024.4.1
![2024-05-03_21-15-34](https://github.com/Olen/homeassistant-plant/assets/46385414/5116b538-aaf7-4e2e-a9f0-49b0da3f865a)

**Comment by Olen** [comment]
Look in the attributes of the plant sensor and see what source sensor it reads data from.

Try the 'replace_sensor' service call (see the readme) to change the source sensors to the correct ones.

**Comment by Malvu** [comment]
to be done manually on all sensors

**Comment by Olen** [comment]
I have no idea how you ended up in this situation. Maybe you have changed the names of the source sensors. Maybe you have done something else. But to set the right source sensor that is the way to do it.
