### ISSUE TITLE
Hard error on HA 2024.6 in `custom_components.plant.group`

### ISSUE THREAD

**Issue by hmmbob** [Olen/homeassistant-plant#168]
Got a hard error in my logs on HA 2024.6.0b4, even though that the component seems to work. I'm running v2024.5.0beta1 version of your component.

> Exception in <function _process_group_platform at 0x7f5c81ffe3e0> when processing platform 'group': (<HomeAssistant NOT_RUNNING>, 'plant', <module 'custom_components.plant.group' from '/config/custom_components/plant/group.py'>) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/group/registry.py", line 44, in _process_group_platform platform.async_describe_on_off_states(hass, registry) File "/config/custom_components/plant/group.py", line 15, in async_describe_on_off_states registry.on_off_states({STATE_OK}, STATE_PROBLEM) TypeError: GroupIntegrationRegistry.on_off_states() missing 2 required positional arguments: 'default_on_state' and 'off_state'

To my understanding, this is different than #167

**Comment by kauthmbt** [comment]
possibly related to [this change](https://developers.home-assistant.io/blog/2024/05/10/group-integration/)
