### ISSUE TITLE
Use `entity_picture` instead of `image` for picture attribute

### ISSUE THREAD

**Issue by piitaya** [Olen/homeassistant-plant#17]
Home Assistant use `entity_picture` for entity image. Do you think it can be good to rename this attribute to be compatible with more custom card integrations?
Source : https://www.home-assistant.io/docs/configuration/customizing-devices/#configuration-variables

**Comment by Olen** [comment]
This is handled in the next version:

https://github.com/Olen/homeassistant-plant/tree/new_plant
