### ISSUE TITLE
Gardena Sensor for Soil humidity is not recognized as entity for the setup and can't be used

### ISSUE THREAD

**Issue by DNier** [Olen/homeassistant-plant#170]
I use the GARDENA smart Sensor from Gardena. The Soil humidity from those sensors doesn't show up in the setup dropdown:

![image](https://github.com/Olen/homeassistant-plant/assets/12126535/02f7ca73-75f0-48cf-a465-ad90247c84fa)

**Comment by Olen** [comment]
Open a bug with the gardena integration to make it use the right device class for its sensors

**Comment by DNier** [comment]
1. Not realy helpful to point to other integrations. Maybe Gardena does it wrong, but for me as a user I don't care who makes the mistake. I want to use the stuff. It worked before and is now broken.
2. What would be the "right" device class other than moisture?

**Comment by Olen** [comment]
1. Not really helpful to behave entitled like this.  Yes. Gardena probably does it wrong.  Ask them to fix it.  I am not going to break this integration to accomodate some other integration that does not work correctly,.
2.  The list of device classes for sensors is available here: https://www.home-assistant.io/integrations/sensor

**Comment by slaxor505** [comment]
@DNier I suggest to use Sensor replacement service as workaround. Just add any available sensor in the setup and then use the service replace the sensor to "unrecognizable" Gardena one. I think it should work until Gardena fixes their classes.

![image](https://github.com/Olen/homeassistant-plant/assets/13409812/d5504f9a-e492-492f-9791-271b10584de2)

**Comment by DNier** [comment]
> @DNier I suggest to use Sensor replacement service as workaround. Just add any available sensor in the setup and then use the service replace the sensor to "unrecognizable" Gardena one. I think it should work until Gardena fixes their classes.
> 
> ![image](https://private-user-images.githubusercontent.com/13409812/342685853-d5504f9a-e492-492f-9791-271b10584de2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTQ4MTYsIm5iZiI6MTcxOTc1NDUxNiwicGF0aCI6Ii8xMzQwOTgxMi8zNDI2ODU4NTMtZDU1MDRmOWEtZTQ5Mi00OTJmLTk3OTEtMjcxYjEwNTg0ZGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDEzMzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkODY0M2UzZWQ1Yjc4M2FhNzdjYTVjNDc4MTk4MGQ1Y2UwZGFjZmM5NDE0OWZjMTkyYTUzZDEwNDE5OTcyNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v20cQc4eAS4fKl3eU-1pKt89Xv5ysOi7YvNx4HWnxS0)

This is realy helpful. Thanks for this Information. Works for me!
