### ISSUE TITLE
Feature Request: Allow non-Sensor entity to be used for Meter entity.

### ISSUE THREAD

**Issue by Kagey-cmd** [Olen/homeassistant-plant#172]
I'd like to be able to use humidity, temperature, etc. data from a weather integration for my outdoor plants. This would eliminate the need to purchase yet another sensor to place outdoors when this meteorological data is readily available.

**Comment by Kagey-cmd** [comment]
Current workaround is to create a template sensor entity, which works fine but seems unnecessary.

**Comment by ChristophCaina** [comment]
A weather integration provides the temperature and humidity information as attribute.
Attributes are not handled the same way as sensor values within HomeAssistant - and therefore, the correct way (even from side of HomeAssistant) is the approach with writing the attribute states into template sensors.

**Comment by TheWarped** [comment]
Openweather creates the sensor "sensor.openweathermap_temperature", and by calling the service in the developer tools "Plant monitor: Replace sensor", that sensor can be associated with a plant.
