### ISSUE TITLE
Integration brakes with the release of HA 2024.7

### ISSUE THREAD

**Issue by corgan2222** [Olen/homeassistant-plant#180]
Hello,

maybe you already know, this, but sadly the whole integration stops working after the update to HA 2024.7 which arrived today.

![grafik](https://github.com/Olen/homeassistant-plant/assets/12233951/a73ace98-5270-4554-853e-82f85f2d25d0)

![grafik](https://github.com/Olen/homeassistant-plant/assets/12233951/13d21cbd-9ebd-492d-8aab-2191d47d81f8)

![grafik](https://github.com/Olen/homeassistant-plant/assets/12233951/af66bcd2-41e9-4fbb-b31e-59a43804c5fc)

vg Stefan

**Comment by Olen** [comment]
Try the latest beta

**Comment by corgan2222** [comment]
Hey Olen,

ah, I totally missed, that there was a beta version as pre-release. Thanks for pointing out.
The good news is, that the plants are back and the loveace card is showing the details. So the update helped a lot.

But If I click on reload on a plant, I get this error.

![grafik](https://github.com/Olen/homeassistant-plant/assets/12233951/57cbf78e-9c0b-4e06-9e0d-92d719eaabfa)

If I change some config values in this plant, the details are coming back, but it still shows this error.

![grafik](https://github.com/Olen/homeassistant-plant/assets/12233951/eb814d49-b05e-4eb4-88b8-4dc23a592486)

Let me know If I can help with testing/debugging. 

vg Stefan

**Comment by corgan2222** [comment]
btw, creating a new plant work without problems.

**Comment by ChristophCaina** [comment]
> But If I click on reload on a plant, I get this error.

reloading the integration caused always this issue in the past.
I think, there was already a ticket open for this.

As far as I remember, this is because the integration doesn't reload anything.
It is basically just collecting the information from the source sensors...

**Comment by Olen** [comment]
Yeah.
There is nothing to reload, so clicking that button is useless

**Comment by chemelli74** [comment]
> Yeah. There is nothing to reload, so clicking that button is useless

Humm, is still not handled correctly as you have a log trace and to recover you need to restart HA.
Do you want a hand to trace it down ?

**Side note**: I changed my plant from "configure" and nothing told me that the new values where loaded in real times, so a reload was the most logic action to take.

**Comment by ChristophCaina** [comment]
hm... I don't have the time / knowledge to look into this as of now (maybe, I will sit down and try to find a way to handle that at some point) - but for anyone who's interested in, this might be the area to look for improvements

https://developers.home-assistant.io/docs/config_entries_config_flow_handler/
