### ISSUE TITLE
Vertical bars only as option

### ISSUE THREAD

**Issue by magune** [Olen/homeassistant-plant#182]
Hi,

I only have 2 bars on each plant, and it would be far better to have them vertically rather than horizontally, as it wastes a lot of screen space:
<img width="1210" alt="image" src="https://github.com/Olen/homeassistant-plant/assets/50596445/79bd5050-66b0-4647-8e17-69a2d5133f36">

If the plant card could optionally show the bars vertically, I can fit in almost 2 times as many plant cards in the same screen space.

**Comment by Olen** [comment]
This is a issue that belongs to the flower card, not the plant integration.

Please provide a PR there.
