### ISSUE TITLE
Configurable name or label

### ISSUE THREAD

**Issue by magune** [Olen/homeassistant-plant#183]
It would be good if the plant card plant name can be overridden using a label or name configuration option.

Now I am stuck with a name I dont want to show on the dashboard:
<img width="249" alt="image" src="https://github.com/Olen/homeassistant-plant/assets/50596445/898311dd-142d-4336-ac81-81b095f0b113">

**Comment by Olen** [comment]
This issue belongs to the flower card, not the plant integration.

Please provide a PR there
