### ISSUE TITLE
Creating a new Plant doesnt use the sensors i selected

### ISSUE THREAD

**Issue by albatrosify** [Olen/homeassistant-plant#187]
I have two Xiaomi BLE Plant sensors.
When creating a new plant, and selecting the sensor with the ID DE61, the integration will always create the plant using the sensor DE5F, eventhough I did not select it.
I am unable to define my plant with the correct sensor.
If i add my both plants with their respective sensor, once i check in integrations, both plants are using the same sensor always.

**Comment by Olen** [comment]
Please see this section of the README:
https://github.com/Olen/homeassistant-plant?tab=readme-ov-file#faq
