### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by CocoLeo3680** [Olen/homeassistant-plant#188]
Hi there

I have installed Plant Monitor to control two plant sensors, a Xioami flora and another unbranded one connected by Bluetooth through Tuya. I have managed to configure more or less all the parameters and the flower card, but I have a battery drain problem.

Each sensor consumes 5% battery per day. What's happening? I guess it's a problem of you getting too many queries.

Any ideas?

**Comment by Olen** [comment]
Hi,

This integration does not touch your physical sensors. It only reads the data that is already in home assistant. 

The xioami integration is completely passive, and only listens for the messages that the physical sensors push at regular intervals, so I don't think that is your problem either. But if you use some other apps on your phone etc, those can probably poll data actively.

**Comment by CocoLeo3680** [comment]
> Hi,
> 
> This integration does not touch your physical sensors. It only reads the data that is already in home assistant.
> 
> The xioami integration is completely passive, and only listens for the messages that the physical sensors push at regular intervals, so I don't think that is your problem either. But if you use some other apps on your phone etc, those can probably poll data actively.

OK thanks. I'll keep and watch.
I have used the HHCC app for 4 years and I have not had battery problems, but it is true that it only sent data when opening the application and it is something that it did infrequently.

**Comment by mihsu81** [comment]
@CocoLeo3680 you'll have to make sure that all the Bluetooth proxies (ESPHome or others) as well as the Bluetooth integration or other integrations use Passive scanning instead of Active scanning. With active scanning the devices are queried for data causing a higher battery drain.

**Comment by CocoLeo3680** [comment]
> @CocoLeo3680 you'll have to make sure that all the Bluetooth proxies (ESPHome or others) as well as the Bluetooth integration or other integrations use Passive scanning instead of Active scanning. With active scanning the devices are queried for data causing a higher battery drain.

Ok thanks. I think that's my fault.
