### ISSUE TITLE
Wrong name in spanish translation

### ISSUE THREAD

**Issue by CocoLeo3680** [Olen/homeassistant-plant#189]
Hi there

First, thanks for this aplication. It is very useful for me
The integration's name showed in spanish is wrong. It calls "Monitor de **planatas**" instead "Monitor de **plantas**"

https://ibb.co/Tg01kGF

Thanks a lot

**Comment by alexsotoaguilera** [comment]
https://github.com/Olen/homeassistant-plant/pull/204

**Comment by Olen** [comment]
FIxed in latest beta
