### ISSUE TITLE
Image not work

### ISSUE THREAD

**Issue by milandzuris** [Olen/homeassistant-plant#192]
Hi i dont see in Card Plant Image where is the problem?

![image](https://github.com/user-attachments/assets/6f6e8970-7105-4d4c-8fef-35efcead79b1)

![image](https://github.com/user-attachments/assets/12875adc-4211-42c8-b3d9-6c4a7a601a51)

![image](https://github.com/user-attachments/assets/77ab01db-7ee1-413d-bf8c-a0ab7b6e97ce)

**Comment by merlin-zaraza** [comment]
Same with me.
I think that it expect to be url, but if you want local file - then path have to start from `\local\` as I can see from [sources](https://github.com/Olen/homeassistant-plant/blob/4ce1c881cbb5f414d2de50e767dc18de00ba7e31/custom_components/plant/config_flow.py#L537). Seems like a bug. Please fix.

**Comment by Olen** [comment]
The path is NOT the path in your file system.
The path is the path to the image from the HA web ui.

**Comment by merlin-zaraza** [comment]
Hi @Olen. So for example HA config is in `/config` file system. Based on that what is the path to the image? My image is in `/config/www/images/plants/zamioculcas zamiifolia.jpg`, but it still not displayed. Could you please make an example?

**Comment by merlin-zaraza** [comment]
Upd. Just realised that it should be `/local/images/plants/zamioculcas zamiifolia.jpg`
