### ISSUE TITLE
HomeAssistant 2024.09 deprecates CONDUCTIVITY 

### ISSUE THREAD

**Issue by chemelli74** [Olen/homeassistant-plant#193]
Here the log of b1:

`2024-08-30 11:20:26.172 WARNING (ImportExecutor_0) [homeassistant.const] CONDUCTIVITY was used from plant, this is a deprecated constant which will be removed in HA Core 2025.6. Use UnitOfConductivity.MICROSIEMENS instead, please report it to the author of the 'plant' custom integration`

**Comment by slaxor505** [comment]
Thanks for reporting it. It will be deprecated in 2025.6 so we have some time.

**Comment by Olen** [comment]
Already fixed in #176
