### ISSUE TITLE
Missing moisture entity. Why the entity is there. !!

### ISSUE THREAD

**Issue by cracyfloyd** [Olen/homeassistant-plant#196]
Any idea why cant see the moisture entity. because the entity is there.

<img width="544" alt="Bildschirmfoto 2024-09-17 um 14 01 18" src="https://github.com/user-attachments/assets/2fa3c836-ffa0-4363-ba20-4f806169d266">

<img width="548" alt="Bildschirmfoto 2024-09-17 um 08 56 16" src="https://github.com/user-attachments/assets/a2730b31-c1af-4c25-8283-264261bf27f6">

under conductivity i see the entity of moisture:

<img width="575" alt="Bildschirmfoto 2024-09-17 um 09 41 02" src="https://github.com/user-attachments/assets/27a9e3f6-2dd4-478b-b730-1a83904df6fd">

**Comment by Olen** [comment]
You are showing the soil-conductivity sensor, not the moisutre sensor.

**Comment by cracyfloyd** [comment]
> You are showing the soil-conductivity sensor, not the moisutre sensor.

Sorry wrong picture. i have the picture updated. Now you can see the entity is there but not possible to select in the moisture field.

**Comment by Olen** [comment]
I guess the sensor does not have the correct device class.

Plase create a PR for the integration you are using for the source sensor to add the correct device class to the sensor
https://www.home-assistant.io/integrations/sensor/#device-class

For now, you can just add some other sensor there and use the "replace sensor" action to change it after the plant was added
https://github.com/Olen/homeassistant-plant?tab=readme-ov-file#easier-to-replace-sensors
