### ISSUE TITLE
Conductivity unit as %

### ISSUE THREAD

**Issue by JohnnyTwoFingers** [Olen/homeassistant-plant#199]
I have three HHCC sensor and they all provide conductivity in µS/cm. I have a plant entity for each sensor and two of the three show the correct unit for conductivity, one shows as %. The only thing I can think of that may be relevant is that the plant with the issue is the second of a particular plant species i added. 

Entity sensor.calathea_exotica_conductivity (<class 'custom_components.plant.sensor.PlantCurrentConductivity'>) is using native unit of measurement '%' which is not a valid unit for the device class ('conductivity') it is using; expected one of ['S/cm', 'mS/cm', 'µS/cm']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/Olen/homeassistant-plant/issues

![image](https://github.com/user-attachments/assets/b19f9707-e6ed-4615-83fc-4106165f37a7)

**Comment by Olen** [comment]
The integration just copies the unit from the source sensor, so it must be a problem with the source.
If you are sure the source sensors are using the correct unit, you could try to use the "replace sensor" action to reset the data from the source sensor.
You probably need to first change it to a different source sensor before you change it back to the correct one.

**Comment by JohnnyTwoFingers** [comment]
thank you

**Comment by ZumZoom** [comment]
Just had the same issue happened to me yesterday. I've set up 7 plants and only one of them triggered the issue. Even though the conductivity sensor was selected correctly it picked up the readings from air humidity sensor instead. The workaround with "replace sensor" worked as intended though.

I can reproduce the error consistently if @Olen you are interested in debugging that one.
