### ISSUE TITLE
Add support for min_battery

### ISSUE THREAD

**Issue by deveth0** [Olen/homeassistant-plant#2]
The original plant component supports a "min_battery" setting which is missing in this fork.

**Comment by TBail** [comment]
Not tested, but i was able to set min_battery while defininga plant

**Comment by slaxor505** [comment]
Yes, it can be done. This component also supports the battery measurments. You just need to add sensor for battery reading like:

`  Hydrangea:
    ...
    sensors:
      ...
      battery: sensor.batt`

**Comment by Olen** [comment]
Just be aware that I am slightly uncertain about this in the future.  The battery status is not really part of the plant itself.  A "plant" is just a "virtual" device and could potentially include many different hardware devices as sensors, each with its own battery.
So it makes more sense to montor the batteries of the physical devices (sensors) than having it as part of the "plant" itself.

But as @slaxor505 mentions, currently it is supported the same way as the original integration.

**Comment by slaxor505** [comment]
I'm thinking to add battery % to the plant-card as here: https://github.com/Hypfer/lovelace-flower-card/pull/3

**Comment by Olen** [comment]
The new plant integration will not provide a battery sensor.  It does not really make sense, as a _plant_ does not have a battery, and a plant device can be built by many different physical sensors, each with its own battery.
You can monitor any battery powered physical sensors by other and better means.

I personally use this blueprint, but there might be other alternatives too.
https://community.home-assistant.io/t/low-battery-level-detection-notification-for-all-battery-sensors/258664
