### ISSUE TITLE
Add humidity measurement

### ISSUE THREAD

**Issue by jhbruhn** [Olen/homeassistant-plant#20]
My plant sensors (b-parasite) measure not only temperature but also humidity. It would be nice if I could integrate that measurement as well. 
What they do not measure is conductivity. Maybe an option could be introduced in the card associated with this integration to replace the conductivity with humidity?

**Comment by slaxor505** [comment]
Do you mean air humidity, right? Why do you want to integrate it, it does not make sense to me - I perhaps don't understand something so please explain. It's likely you wish to have an average.

**Comment by jhbruhn** [comment]
I do mean air humidity, right. And sorry for the wording. I didn't mean integrate in a mathematical sense, but as in "integrate a humidity feature into this card" :)

**Comment by slaxor505** [comment]
Got it :) Thanks for explanation.
Plantbook API provides humidity value... so you want to monitor humidity for a plant and see it on PlantCard, right?

**Comment by jhbruhn** [comment]
Correct. As having five values destroys the symmetry a bit, my suggestion is to make the conductivity value (or perhaps all values?) optional for sensors which don't provide that, as does the b-parasite sensor.

**Comment by Olen** [comment]
If we are able to re-make the plant component, to create each plant as a "device" with config parameters and (optional) sensors, it would make a lot of sense.
A problem is that HA is not really designed to allow a "device" to depend on (or get data from) "3. party" sensors.  A device is supposed to be a self contained unit.  Whereas a "plant" in this case consists of a set of config parameters (min/max values for different measurements) and one or more external sensors to provide the actual measurements.
Today, we basically call a multi-sensor (e.g. a VegTrug or other similar hardware) a "plant", but the sensor itself is not really the plant.  These need to be separated.  What I would like to have is the sensor(s) acting as just a sensor, providing one or more regular entities.  And then have a plant-"device", which bundles these individual sensor-entities.

That way we can say that my "plant"-device has this set of config-entities (min/max-values, spieces etc.) and it has a set of sensor-entities, which are just references to exisiting HA-sensors.
That way I can make any plant read data from any sensor, and I can use one air-humidity-sensor in the living room for ALL the plants in that room, if I don't have individual air humidity sensors for all the plants for instance.

**Comment by Olen** [comment]
I am currently completely rewring this integration, and the new one will have the option to add (air) humidity as a sensor.

Here is a sneak peek into what I am working on:

![image](https://user-images.githubusercontent.com/203184/180448544-d06d6404-1936-4184-9510-f9a1bcb7f6d7.png)

Just notice that the plant integration itself is cmpletely independent from the flower card in lovelace.
So even after I add a humidity sensor to the plant integration, it would also need to be added to the flower card, if you need it there.  While I work on the new plant integration, I will have a look at making the flower card more flexible as well, to allow you to select which values you want to show.

**Comment by Olen** [comment]
Updated flower card

![image](https://user-images.githubusercontent.com/203184/180458385-d3af34ce-bbee-4c1d-abcc-f34027889ff2.png)

**Comment by Olen** [comment]
Humidity sensors (air) will be possible to configure in the next version.

https://github.com/Olen/homeassistant-plant/tree/new_plant
