### ISSUE TITLE
Sensor value for min_moisture

### ISSUE THREAD

**Issue by dingausmwald** [Olen/homeassistant-plant#26]
Maybe i do something wrong, but i am not able to put a (statistics) sensor value for min_moisture like this

`min_moisture: {{ states('sensor.max_feuchtigkeit_sensor_1') | int / 2 }}`

my goal is to warn whenever the waterlevel is below half the max moisture.
I created a statistics sensor which does work. But when i paste this in the .yaml the plant cards don't show. There is no error in the logs asswell.

**Comment by Olen** [comment]
I don't think you can use templates in the config like that.

However there is a completely rewritten version coming up soon, where you can more easily select the sensors you want to use - just ensure that they have the correct DeviceClass.

https://github.com/Olen/homeassistant-plant/tree/new_plant

I use "humidity" for both moisture and air humidity in the new version.

https://www.home-assistant.io/integrations/sensor/

**Comment by Olen** [comment]
Closing this as the upcoming release does not support yaml-config anymore
