### ISSUE TITLE
Possible problem with image retrieval

### ISSUE THREAD

**Issue by iMiMx** [Olen/homeassistant-plant#32]
Have updated both the integration and the frontend card, upgrade worked pretty well.

However, I don't seem to have images.  Even though the species migrated across correctly and has been manually verified.  If I manually populate the URL from openplantbook, then it displays with the card.

Using beta5 of the card and v2.0.0-beta.11 of the integration.

![LvlCaT0y](https://user-images.githubusercontent.com/17220013/184910229-00550d37-dd64-4eda-821e-505bacd8b92c.png)

![tkhhsR0P](https://user-images.githubusercontent.com/17220013/184910286-78f00a54-6825-496b-985f-b04d48313821.png)

Species and Species to display set to:

`dionaea muscipula
`

**Comment by Olen** [comment]
It seems like you don't have the Openplantbook integration installed. Can you verify that it is installed and working by doing eg. a Openplantbook.search service call?

**Comment by iMiMx** [comment]
My apologies, you are absolutely correct - I missed/forgot to install:

https://github.com/Olen/home-assistant-openplantbook
