### ISSUE TITLE
Unable to add plants that are not in Openplantbook

### ISSUE THREAD

**Issue by syphernl** [Olen/homeassistant-plant#34]
With [v2.0.0-beta.12](https://github.com/Olen/homeassistant-plant/tree/v2.0.0-beta.12) and the OpenPlantbook API I am unable to add my "Euphorbia Trigona":
```
Did not find «Euphorbia Trigona» in OpenPlantbook. Using default values for thresholds.
```

However, clicking submit results in seeing the spinner for a while and nothing happens. The call to `/api/config/config_entries/flow/xxxxx` however gives a `200` yuet the response body contains the form again.

Payload:

```json
{
   "display_pid":"Euphorbia Trigona",
   "max_moisture":60,
   "min_moisture":20,
   "max_illuminance":100000,
   "min_illuminance":0,
   "max_dli":30,
   "min_dli":2,
   "max_temperature":40,
   "min_temperature":10,
   "max_conductivity":3000,
   "min_conductivity":500,
   "max_humidity":60,
   "min_humidity":20
}
```

**Comment by Olen** [comment]
Should be fixed in #34.

Might also require you to update to the latest version of the Openplantbook integration.
