### ISSUE TITLE
Air humidity sensor instead of moisture sensor

### ISSUE THREAD

**Issue by mia-letum** [Olen/homeassistant-plant#40]
I have two plants. One plant working well, but other plant have wrong moisture information. It get's air humidity instead of moisture.
Even if i delete plant and add again with correct sensor it's have wrong data.
Even if i delete plant and add without moisture and air humidity sensor it's have air humidity in moisture.

**Comment by Olen** [comment]
What version are you using?
This behaviour seems very strange, as the integration will not add any other sensors than the ones you select when you add a plant.
Can you show me the attributes of the two sensors in question (air humidity and soil moisture)?

You can also use the "Replace sensor" service call to set the correct external sensor.

**Comment by mia-letum** [comment]
I'm using 2.0.0
First time plant was created on beta2 or beta3

What attributes do you need and how cen i get in?

**Comment by Olen** [comment]
I am preetty sure this was due to HA caching
