### ISSUE TITLE
[Feature request] Add possibility to change sensor

### ISSUE THREAD

**Issue by bernji** [Olen/homeassistant-plant#41]
Love the integration together with the Plant card! Awesome work with the redesign!

I hade not set the air humidity sensor (left blank) and I could not find how to set it once it's setup.
The only possibility I have found was to delete the wohle plant and readd it with a humidity sensor

I could find the text when configuring "If you can't find the correct sensors in the dropdown menus, sensors can be added after the plant is set up". But how am I doint this? When I edit a plant in the integration menu I can only add the triggers for a problem, species and picture but not the sensors.

Can you please make that edditable or am I missing something?

**Comment by Olen** [comment]
As described in the readme, you can use the "replace sensor" service call to do that.

**Comment by bernji** [comment]
I see. Thank you
