### ISSUE TITLE
Expose what the problem is

### ISSUE THREAD

**Issue by greghesp** [Olen/homeassistant-plant#43]
When looking at a device, if you're not using the flower card, it is not clear as to what the problem with a plant actually is.
As per this example, there's an issue, but no indication of what it is.

This would be handy to have for automations, maybe by saying a plant needs feeding, watering, more light etc

![image](https://user-images.githubusercontent.com/768908/189962927-224b7593-2e3e-442e-bb10-8f8b33bec414.png)

**Comment by Olen** [comment]
The reason for "problem" state is set as attributes of the plant entity (plant.your_name)
