### ISSUE TITLE
[Question] Duplicated sensors generated by integration

### ISSUE THREAD

**Issue by syphernl** [Olen/homeassistant-plant#45]
When configuring a new instance of Plant Monitor you get asked for temperature/moisture/conductivity etc sensors which pre-exist and are used by the integration. 

![image](https://user-images.githubusercontent.com/639906/189972602-b4f23428-1d6b-49f2-919e-d8d17c9c430a.png)

In entities view;
![image](https://user-images.githubusercontent.com/639906/189973000-956d9052-c0d4-4f8c-9624-8078f1c6ad36.png)

If I disable the Plant Monitor-generated sensors (in order to clean up the number of entities in my HASS install) the Plant card stops working.

What is the use-case for this integration to re-expose these sensors again?

**Comment by Olen** [comment]
This is by design.  The plant **device** has its own sensors and helpers to keep it consistent and self contained.  Also, it means that you can change and replace your external sensors and still keep long term data and statistics for your plant sensors, which is mportant for many users.

**Comment by syphernl** [comment]
Makes sense, although it would not have been my preference as it leads to (more or less) duplicate entities and storage usage. 

In order to prevent duplicate storage of both sensors I have disabled the "source" sensors in the HASS History recorder. 
Perhaps this could/should be added as a suggestion to the documentation?
