### ISSUE TITLE
Integration error setting up a new plant from scratch

### ISSUE THREAD

**Issue by cromelex** [Olen/homeassistant-plant#46]
Hi,

I have just installed this and have the OpenPlantbook integration working properly (tested with the service call and it is returning results as expected). I installed from scratch, so I did not have any plants configured in my configuration.

If I set up a plan using the integration without a species, I get a "uknown error" on top of the screen. 
If I fill in the species, it looks up the plant on the OpenPlantbook database, shows me a screen where I can select the correct species, but if I continue I get an error.

In my HASS log I can see this error being triggered anytime I try to set up a plant:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 178, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/plant/config_flow.py", line 115, in async_step_user
    return await self.async_step_select_species()
  File "/config/custom_components/plant/config_flow.py", line 190, in async_step_select_species
    return await self.async_step_limits()
  File "/config/custom_components/plant/config_flow.py", line 371, in async_step_limits
    entity_picture = f"{get_url(self.hass, require_current_request=True)}{urllib.parse.quote(entity_picture)}"
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

I tried just for the sake of it to try and config a plant in my configuration using the HASS native integration, and this integration successfully picked it up, so I am not sure what exactly is going wrong here.

Any advice or anything I can do help figure this out, if it is a bug?

**Comment by Olen** [comment]
Now, I am not 100% sure, but it looks to me as if it can't find the URL for the image of the plant.
It is trying to use the URL of your home assistant installation, by calling `"get_url(....)"`, and this fails, so it might be that you have not specified the correct url to your HA installation in the settings?

Here is a similar bug report from another integration with the same error message:
https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/issues/35#issuecomment-718070847

I'll see if I can add a similar fix as in that ticket to at least give a better error message if it happens again.
But in short - make sure you set the internal_url and external_url 
https://www.home-assistant.io/docs/configuration/basic/

**Comment by cromelex** [comment]
Okay, interesting one. 

I can't change the URLs as basically I use Nabu Casa for external access, but for internal access I am using HTTPS. I am using homeassistant.mydomain.xy with a DNS redirect to my local IP, allowing me to have HTTPS on the internal domain without exposing externally and without triggering browser errors.

![image](https://user-images.githubusercontent.com/96779452/191252537-446a6ebc-1071-450b-98ca-55853836cb3b.png)

The error happens even if I don't set a species.
Could the flow somehow be changed to skip that network request? If I set up a test plant manually, with just the name, it still triggers the error.
I haven't seen this error anywhere else, the plant image downloaded fine and I am able to see it externally. 

I've actually ordered a few more plant sensors so intend to set up a few more plants. 
I understand my setup as per the above might be quite specific, so not many people are likely to see the same error, but even if I could set up the plants as "shell" in the UI and then just configure the species and sensors after, that would help.

If not - setting them up manually in the configuration for the native/legacy HASS plant integration and then reinstalling this so it picks them up should work, as thats what I did as a workaround the first time around.

Thanks,

**Comment by cromelex** [comment]
I'm away from home for a couple of days, once I am back I will test and let you know.

Thanks

**Comment by TomStarren** [comment]
I had this same issue, I can confirm setting the internal_url fixes the issue. When I tested your modified file I got an error that the integration doesn't support the GUI

**Comment by cromelex** [comment]
I can confirm the modified file throws an error, ie integration doesn't support GUI.

This is the error log:
Logger: homeassistant.config_entries
Source: config_entries.py:796
First occurred: 09:28:35 (1 occurrences)
Last logged: 09:28:35

Error occurred loading configuration flow for integration plant: Exception importing custom_components.plant.config_flow.

I went ahead and specified the internal_url. It does fix the issue.
I am not too familiar/comfortable with the whole SSL/HTTPS config in HASS, and it was HASS itself that set the interal_url to "automatic" (rather than leaving a blank field), so to be honest I was a bit afraid of messing something up.
It doesn't. It is working fine.

My suggestion would be for you to go back to your first thought and get the error handling to just tell people to set up the internal_url.

Thanks again for the support and your work on this integration.

**Comment by Olen** [comment]
Found a stupid typo.  Fixed now.  Released a beta that should fix this issue
