### ISSUE TITLE
Feature request: expose overall problem state for device automation

### ISSUE THREAD

**Issue by microraptor** [Olen/homeassistant-plant#48]
I want to create an automation and use the plants problem state as a trigger and I would assume getting a notification, if there is a problem with the plant would be a popular use case. However, if I choose a device trigger and select the plant ("Imperial White" in this example), only value changes are selectable:
![image](https://user-images.githubusercontent.com/15663536/192845668-776f0173-5fd7-4c34-aa3f-eb1bf86181cd.png)

It would be very convenient to also have the option "plant status changed to problem", which then depends on which sensors are configured as problem triggers in the device options.

The only way to currently achieve this is to set an entity trigger and set the "from" and "to" fields to "ok" and "problem" (I actually haven't tested this yet). This is less elegant and less intuitive than the previously suggested method, where people would just select it in a dropdown menu.

**Comment by Olen** [comment]
It would be nice, but currently the "plant" integraion is not very well handled by HA (which is why I created this replacement in the first place).
To get this working, I would have to change it from a "plant" entity to a "binary_sensor", OR we would need some major changes to HA core (please feel free to submit PRs if you want).

**Comment by Olen** [comment]
Closing this as it depends on core changes that probably will not be added in any reasonable timeframe

**Comment by microraptor** [comment]
Thank you for the answer and giving it some thought. All what would be needed for now to make an automation work, would be an additional sensor created by this integration like `binary_sensor.NAME_plant_problem` which reflects the problem state of the main plant entity.

**Comment by Olen** [comment]
That could be an option.  Or you can just make a template-sensor.
I can reopen the issue and give the addition of a problem binary sensor some more thought.
Don't hold your breath, though...

**Comment by microraptor** [comment]
I remember trying to make a template-sensor before I opened this issue. Unfortunately it was pretty difficult.

**Comment by Olen** [comment]
I think it is pretty trivial to create template sensors.  In templates.yaml (or similar):
```
- binary_sensor:
  - name: "Plant1 problem"
    state: "{{ is_state('plant.monstera', 'problem') }}"
    device_class: "problem"
  - name: "Plant2 problem"
    state: "{{ is_state('plant.smaragdpalme', 'problem') }}"
    device_class: "problem"
```

![image](https://github.com/Olen/homeassistant-plant/assets/203184/5d7fc2c4-ff37-43b4-8fd6-63c622ec7cb8)

![image](https://github.com/Olen/homeassistant-plant/assets/203184/2fb54cfd-2066-4bc6-ac94-7b3b5e69b8a8)

Of course, you can do any kind of funny stuff with the template sensors, including adding attributes and icons and images and stuff.  This was just the smallest example I coud come up with.

https://www.home-assistant.io/integrations/template/

**Comment by microraptor** [comment]
Thank you! While creating an automation for the template sensors, I noticed that Home Assistant automations actually supports the plant entities now.

As a trigger:
![image](https://github.com/Olen/homeassistant-plant/assets/15663536/da8408f4-3443-4260-a5ab-b7c34215eb37)

As a condition:
![image](https://github.com/Olen/homeassistant-plant/assets/15663536/7171ab66-3a03-40bf-83cc-5852b949b0bd)

**Comment by wehrstedt** [comment]
> I think it is pretty trivial to create template sensors. In templates.yaml (or similar):
> 
> ```
> - binary_sensor:
>   - name: "Plant1 problem"
>     state: "{{ is_state('plant.monstera', 'problem') }}"
>     device_class: "problem"
>   - name: "Plant2 problem"
>     state: "{{ is_state('plant.smaragdpalme', 'problem') }}"
>     device_class: "problem"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/203184/257552209-5d7fc2c4-ff37-43b4-8fd6-63c622ec7cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzE4MzgsIm5iZiI6MTcwNTc3MTUzOCwicGF0aCI6Ii8yMDMxODQvMjU3NTUyMjA5LTVkN2ZjMmM0LWZmMzctNDNiNC04ZmQ2LTYzYzYyMmVjN2NiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNzI1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2VhYWE5ZmMwYzU5Mjk5Y2U1OTQzN2QwMjAwNjJhNjAzYzc3MmVhMWZlNzA2Yjc5NzVmNDc0Yjg3OTg0YjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h_TAZYIFz8S97If2RNT8I2aSsGKNGuhVlhJKVbpTydw)
> 
> ![image](https://private-user-images.githubusercontent.com/203184/257552537-2fb54cfd-2066-4bc6-ac94-7b3b5e69b8a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzE4MzgsIm5iZiI6MTcwNTc3MTUzOCwicGF0aCI6Ii8yMDMxODQvMjU3NTUyNTM3LTJmYjU0Y2ZkLTIwNjYtNGJjNi1hYzk0LTdiM2I1ZTY5YjhhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNzI1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzljNDg5OGNmZWY4MTBkODM1OWUzYmRmOGIyMDNlODk2MmQwNGIzZDgxMWE4YjUyOWQzMjNhMjJiNGFjYTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CErpUhu9bSL_ykXNffK8WOmZgYzQpZM95hOlLBOqMtM)
> 
> Of course, you can do any kind of funny stuff with the template sensors, including adding attributes and icons and images and stuff. This was just the smallest example I coud come up with.
> 
> https://www.home-assistant.io/integrations/template/

I did something similar for my window sensor to make a "all windows open / closed" sensor without having to handle every window sensor by itself. This is a more generic aproach and can be used for an automation trigger without the need to update the automation trigger if you add a new plant:

```
 binary_sensor:
    - name: "Alle Fenster"
      unique_id: "alle_fenster"
      device_class: "opening"
      state: >
        {% set items = states
          |selectattr('attributes.device_class','eq','opening')
          |rejectattr('entity_id', 'eq', this.entity_id)
          |selectattr('state', 'eq', 'on')
          |map(attribute='entity_id')
          |list
        %}
        {% if items | count > 0 %}
          {{ True }}
        {% else %}
          {{ False }}
        {% endif %}
```

Didnt testes this but i think you can create a similar template sensor for the plants by filtering the equivalemt device class
