### ISSUE TITLE
Error in external and internal url detection

### ISSUE THREAD

**Issue by archit3kt** [Olen/homeassistant-plant#51]
Hi,

Updated to latest HA and your integration to 2.0.1, plant adding now works but I've got this error message :

Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.plant.config_flow
Source: custom_components/plant/config_flow.py:184
Integration: Plant monitor ([documentation](https://github.com/Olen/homeassistant-plant/), [issues](https://github.com/Olen/homeassistant-plant/issues))
First occurred: 9:57:12 PM (5 occurrences)
Last logged: 10:06:08 PM

No internal or external url found. Please configure these in HA General Settings

It seems you're not detecting correctly URL in the configuration.yaml file since it is defined as shown in screenshot

![Screenshot_20221023_221128](https://user-images.githubusercontent.com/32200831/197416033-eca59fa9-8b2a-42b5-bb11-55208ab79f5a.png)

**Comment by Olen** [comment]
I am using the built in function "get_url()" so it's not much I can do here I think.
Are the URLs showing up in the General Settings in the UI?

**Comment by archit3kt** [comment]
I commented out these lines in my configuration.yaml to see if these parameters are all configurable in UI

Here is the result 

![Screenshot_20221024_153638](https://user-images.githubusercontent.com/32200831/197539311-d63efb00-1cc9-4e62-9263-8512c383be40.png)

I don't know of a UI way to configure these parameters, is it supposed to be shown somewhere ?
