### ISSUE TITLE
dli status reports Low, even though the value is within the range

### ISSUE THREAD

**Issue by LeChuck2909** [Olen/homeassistant-plant#57]
The dli range has been set from 2 to 30 to be ok. the current value is 10. still the plant state is "problem" and the attribute dli status reports Low.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/61522664/212135086-8ec4a4af-0f72-4ec7-81b6-073e28990747.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/61522664/212135115-a631c95d-4e42-4c4f-b25b-2a071ec082a0.png">

**Comment by MackoMici** [comment]
is wrong for me too

**Comment by Knobiwahn** [comment]
got the same....

**Comment by ChristophCaina** [comment]
Hi there :)

I have observed a similar behave, but it is not quite clear to me, when the information should show "OK", "High" or Low...
the Indicator is showing too low in any case:

Plant 1:
![image](https://github.com/Olen/homeassistant-plant/assets/26391061/f4a7d250-8163-47ca-a8eb-cc54fc50417c)
![image](https://github.com/Olen/homeassistant-plant/assets/26391061/c719c2dd-8f4f-4f8d-ba9f-63d64fbacd3f)

Plant 2:
![image](https://github.com/Olen/homeassistant-plant/assets/26391061/7451a17c-d150-4eff-bb3e-3309d254a63c)
![image](https://github.com/Olen/homeassistant-plant/assets/26391061/ec525476-b4ff-4f84-9469-06d591491035)

Plant 3:
![image](https://github.com/Olen/homeassistant-plant/assets/26391061/a2a579be-19dd-49d9-912b-313773bed547)
![image](https://github.com/Olen/homeassistant-plant/assets/26391061/1e38f8c5-4595-4030-8c95-40c70be53a31)

**Comment by Olen** [comment]
If you look at the developer tools, what is the real status of the dli-sensors?
Could this weird behaviour be connected with your strange "s"-es in the unit?
I still have a feeling that this is related somehow to HA trying to be smart about the units, and converting the displayed data from days to seconds or vice versa.

**Comment by ChristophCaina** [comment]
I guess, I know how the attribute for DLI is now working...

LOW / HIGH / OK is referring to the last state.
So while the card is showing the current status while it is "collecting" the data, the attribute is showing the information how it was in the last cycle.

I had some plants outdoor the last couple of days - and the information is now showing "high" for most of them - while the sensor is still collecting and the plants are inside now.

The Card is showing a too low current value...

**Comment by ChristophCaina** [comment]
> Ah, yes you are right. DLI warnings are based on the state from the end of last cycle. Or else it would altert for "low" every morning (from midnight) until the number has crawled up during the light period.

which would be OK in my eyes... ?

**Comment by Olen** [comment]
An alarm that is triggered consistently every night is not really useful.
DLI is not something that requires instant attention anyway.  There is not a _problem_ that it is dark from midnight until the morning.  But it might be a problem if a plant does not receive enough light (or maybe too much light) in sum throughout the day.
So it makes more sense to base the alerts on the previous full 24 hours than an instant value that you _know_ will be too low for many hours every night.

**Comment by Olen** [comment]
Closing a few old issues
