### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'plant'.

### ISSUE THREAD

**Issue by XxCabbyoO** [Olen/homeassistant-plant#6]
No 'version' key in the manifest file for custom integration 'plant'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'plant'

**Comment by XxCabbyoO** [comment]
Can you fix it?

**Comment by Olen** [comment]
It's there:
https://github.com/Olen/homeassistant-plant/blob/master/manifest.json
Added back in April:
https://github.com/Olen/homeassistant-plant/commit/85ca8bbb1e92fa6eabe37bace0fe9de4234d14f4
