### ISSUE TITLE
Feature: Sensor upload - Help needed.

### ISSUE THREAD

**Issue by slaxor505** [Olen/homeassistant-plant#61]
Please help with the implementation of the sensors upload feature of Open Plantbook as described here:
https://documenter.getpostman.com/view/12627470/TVsxBRjD#9728f561-a05b-4886-ba29-25722819150c

**Comment by slaxor505** [comment]
I've just released the first version of Python Library to handle JSON-Timeseries (JTS) specification handler. It can be used to easily pack and unpack sensor data in JTS format and push it to OpenPlantbook.
https://github.com/slaxor505/json-timeseries-py

**Comment by slaxor505** [comment]
PR with this functionality has been submitted: https://github.com/Olen/home-assistant-openplantbook/pull/12
@Olen Please approve.

**Comment by Olen** [comment]
This belongs to the openplantbook-integrations
