### ISSUE TITLE
Commits missing from the repo?

### ISSUE THREAD

**Issue by d0ugal** [Olen/homeassistant-plant#63]
This is a bit of an odd one, but I was evaluating using this repo and noticed this when I view the latest tag. It suggests there is a change on the tag that isn't in the master branch - this could be a problem later. Anyway, I figured I'd mention it incase you didn't know!

https://github.com/Olen/homeassistant-plant/tree/2.0.2

<img width="884" alt="Screenshot 2023-03-13 at 20 14 53" src="https://user-images.githubusercontent.com/48211/224821992-fb1464ef-05b9-4abd-a966-3e3748991e68.png">

**Comment by Olen** [comment]
Thanks.
It was just setting the correct version string in the manifest.  But I added a commit now, so it should be correct.
