### ISSUE TITLE
Feature: Update/change sensors configured.

### ISSUE THREAD

**Issue by Fonsos** [Olen/homeassistant-plant#68]
We have to select some sensors when creatin a plant, if we didn't selected a sensor and want to add it later, we have to delete all the plants we want to update and create them again one by one.

Maybe on the configuration of the plant we could be able to change all the sensors so we can update them without delete all the plants.

When you have 2 or 3 plants, there is no problem, but when you have more than 10, it becomes trouble.

I have several plants created and now I got an humidity sensor and I have to update one by one by deleting and creating them again. And if in a future, if we move plants with a sensor to another pot with anther sensors, we could change it quickly.

**Comment by Olen** [comment]
Please read 
https://github.com/Olen/homeassistant-plant#easier-to-replace-sensors

**Comment by Fonsos** [comment]
Thanks, didn't know that it existed.
It would be awesome if it could get into the configuration interface to do it easily.

Thanks!

**Comment by Olen** [comment]
It is very limited what can be done in the configuration/"options" interface.  That is why I had to make this as a separate service.
