### ISSUE TITLE
Error after Home Assistant Core upgrade 

### ISSUE THREAD

**Issue by ozzinse** [Olen/homeassistant-plant#7]
After upgrade to new version i have error 
[homeassistant.loader] The custom integration 'plant' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

Can You fix it please ?

**Comment by Olen** [comment]
This was fixed back in April.
Please update your installation

https://github.com/Olen/homeassistant-plant/commit/57a5a1b42333b50e2625ad3b66a9bd99087a001d
