### ISSUE TITLE
Problem state attribute

### ISSUE THREAD

**Issue by rubdos** [Olen/homeassistant-plant#70]
With the default Home Assistant plant integration, I had some automations that queried the `problem` state attribute, e.g. for use in notifications:

```jinja
{{ state_attr('plant.punica_granatum_nana', 'problem') }}
```

Is there an equivalent for this integration?

**Comment by Olen** [comment]
The "problem" has been moved to the actual state of the "plant.xxx" device itself.
And the device have multiple attributes to show what the problem actually is:

![image](https://user-images.githubusercontent.com/203184/235158320-9e551591-ab3a-48c3-9693-632b29bf1e2e.png)

**Comment by Olen** [comment]
Yes. I changed that to individual attributes per "problem" to make it easier to create different alerts or automations based on what the problem actually is.
You can easily create a single template by combining the attributes as you want.
