### ISSUE TITLE
opening sensor card displays "no statistics found" 

### ISSUE THREAD

**Issue by morris2009** [Olen/homeassistant-plant#71]
When I open the sensor card for conductivity it displays the value of the sensor but  there is no graph, only the text "no statistics found".
If i click on Show More, then i the history page for that sensor opens, and there is an up2date graph available for that sensor.

This only happens for 1 sensor, the conductivity sensor of a plant.

![image](https://user-images.githubusercontent.com/6625837/236341314-0729260b-18bb-490d-b5f4-c27462d63e6e.png)

**Comment by Olen** [comment]
This graph is created by HA, and is not controlled by the card.
You need to check if you have ignored history for this sensor or maybe something is wrong with your database.
