### ISSUE TITLE
Specify when plant was last watered

### ISSUE THREAD

**Issue by quentinus95** [Olen/homeassistant-plant#73]
It would be interesting to have an option to (manually) specify when a plant was watered (and display it on the card).

I'm using a separate blueprint today but it would allow to group information for each plant and have an alert if plant was not watered for a specified time.

Useful for plants without a moisture sensor.

**Comment by magune** [comment]
why would you want to enter that manually? if you have soil moist sensor in the plant, the sensor readings clearly show when the plant was watered? with that said, I agree it would be nice to have the card say something like "watered 5 days ago", but it shouldn't be entered manually But sensor driven

**Comment by quentinus95** [comment]
Hello, thanks for your answer!

> if you have soil moist sensor in the plant, the sensor readings clearly show when the plant was watered?

I'm precisely specifying in my message that it would be useful for plants without a moisture sensor.

**Comment by Olen** [comment]
I think this issue would be more relevant in the flower-card repo, if you just want it displayed in the plant card.
There are more suitable ways of specifying dates/times in HA than in the plant integration.  Creating a simple helper for each plant would give you the necessary inputs, and you can create as many automations and alerts as you want based on them.

_However_ I don't think I am going to implement this in the flower-card.  But I will look at a PR if you can make one that makes sense in the flower-card repo.
