### ISSUE TITLE
Device class issues for the Plant attributes

### ISSUE THREAD

**Issue by posreg** [Olen/homeassistant-plant#74]
Good Morning!

I think I have tried all steps described in the last posts but still not able to have the Plant fully functional.
If my question is dumb - just say it!

After update to ``` 2023.04``` I've noticed problems, as described in different thrreads.
I've waited for component update and performed the Plant Upgrade + HA Upgrade (05.02)  yesterday

When configuring the plant got following errors:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plant/__init__.py", line 627, in update
    and self.sensor_moisture.state != STATE_UNKNOWN
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.miflora1_soil_moisture has device class moisture, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)
```
What concerns me, is that seems like integration is not pulling the data from my sensors, or am I getting this wrong ?
Integration is pulling the data from the sensors that does not exist even though I;ve configured Plant to use working sensors
![image](https://user-images.githubusercontent.com/80816020/236788211-f291e086-7a34-4444-93a0-75e5d0404702.png)

![image](https://user-images.githubusercontent.com/80816020/236788361-83e42fd9-76d4-44dd-b56b-ef7281dbef70.png)

![image](https://user-images.githubusercontent.com/80816020/236788535-f9616600-5bbd-465d-8d90-7212b8017652.png)

Any advice please ?

**Comment by the-jeffski** [comment]
I'm seeing this too - I think it seems to happen to me if the sensor goes unavailable.

**Comment by posreg** [comment]
it was my bad! I didn't realize that I can use replace_sensor service...
closing!
