### ISSUE TITLE
DLI value not calculated?

### ISSUE THREAD

**Issue by magune** [Olen/homeassistant-plant#77]
Fantastic integration & dashboard card! With that said, I don't get the DLI value to be displayed. I have miflora plant sensors that report light, and I did get an auto created dli entity for the plant. but it isn't calculated, value is always 0 despite realtime light level being reported correct. 
![image](https://github.com/Olen/homeassistant-plant/assets/50596445/ca1aefcb-dbe6-4326-979e-5d0285c6264f)

**Comment by magune** [comment]
just realized it resets itself at midnight and I haven't had a lot of light since then

**Comment by ryoko-sky** [comment]
Hello. I have the same problem, but I have artificial lighting as well as a light cycle per day.
Please add the ability to manually select the reset time. When growing artificially, the correct calculation of dli is very important
