### ISSUE TITLE
No images showing

### ISSUE THREAD

**Issue by Davst** [Olen/homeassistant-plant#8]
Just added this integration with the flower card that you've developed. 

I've had a look in the plant database and the plants I added have images listed in the database, however the images appear to be broken in the dashboard, they all point to the local fallback folder so it seems like the plants aren't pulling the correct image location from the db?

**Comment by slaxor505** [comment]
My understanding is that it has not been implemented yet.

**Comment by slaxor505** [comment]
It is fixed now. Pending this pull request: https://github.com/Olen/homeassistant-plant/pull/10
Meanwhile you can take updated component from my repository: https://github.com/slaxor505/homeassistant-plant

**Comment by olskar** [comment]
I have set "image: openplantbook" and the image exists at https://open.plantbook.io/api/v1/plant/detail/sansevieria%20trifasciata/

However it still tries to load xxxxxxxx/local/images/plants/sansevieria%20trifasciata.jpg that does not exist, so I get no image for the plant

**Comment by slaxor505** [comment]
Can you double-check that you are using the latest version from repo.

**Comment by greghesp** [comment]
@slaxor505 I've set mine to openplantbook using the latest version, but it seems to actually be using `openplantbook` as the URL:

```
  pachira_aquatica:
    species: Pachira macrocarpa
    image: openplantbook
```

`<img src="openplantbook">`
