### ISSUE TITLE
Plant status shows "unknown" for all plants

### ISSUE THREAD

**Issue by syphernl** [Olen/homeassistant-plant#84]
For some reason all of my plants show status `unknown` 

They are all configured like this one:

![image](https://github.com/Olen/homeassistant-plant/assets/639906/244e25ad-257a-4052-b7e2-78c14d3d90c1)

All of these checked sensors show up and have values:

![image](https://github.com/Olen/homeassistant-plant/assets/639906/eff09687-06d0-426c-8da3-c0352856b685)

Integration version: 2.2.0-beta1

**Comment by kohlerryan** [comment]
+1
