### ISSUE TITLE
'Unkown error occurred' when adding plant.

### ISSUE THREAD

**Issue by xanox1** [Olen/homeassistant-plant#86]
Unsure how i got into this situation, but i cant add any more plants for reason: Unkown.

I have 6 plants setup succesfully and working as intended. But when i try to add a new plant now, i simply get 'Unkown error occurred'

Please find the debug log attached. 

[home-assistant_plant_2023-07-18T19-42-19.654Z.log](https://github.com/Olen/homeassistant-plant/files/12088491/home-assistant_plant_2023-07-18T19-42-19.654Z.log)

**Comment by xanox1** [comment]
Oh i forgot to mention that it wont matter if i add sensors or not. The debug log is where i added no sensors to exclude any problems on that end.

**Comment by Sakynet** [comment]
+ 1

**Comment by larronni** [comment]
+1
