### ISSUE TITLE
Strange tiling of plant cards.

### ISSUE THREAD

**Issue by surskitt** [Olen/homeassistant-plant#9]
I'm aware this isn't the perfect place to be posting issues about the card, but there's no issue tracker on that repo.

I'm seeing some funny issues with the tiling of the plant card. On this monitor I should be seeing 3 columns, but on views with the plant card I only ever see a max of 2. Does anyone have any ideas why this may be happening? I don't think it's my setup since other views show the 3 columns fine.

![Plant cards](https://0x0.st/-ODB.png)

Thanks.

**Comment by slaxor505** [comment]
Sorry for such a late response. It seems to be working fine for some people. Judging by the screenshot, it looks like that 3rd column is not fitting a bit. Better place to raise it here https://github.com/Olen/lovelace-flower-card

**Comment by shanedabes** [comment]
I can't raise issues on that repo since it's a fork. Also, your screenshot doesn't seem to be using that card.

**Comment by ristomatti** [comment]
I have a possibility related issue. On my phone the tabs with plant card scroll horizontally even thought everything fits on screen. I suck at CSS but I'll have to dig into this with brute force trial/error technique sooner or later unless some CSS wiz turns up!

**Comment by ristomatti** [comment]
One thing to note is that I quickly skimmer though the card code and noticed the CSS used `#` (id) selectors with generic names. AFAIK this is against the spec and some styles might not be correctly applied if there's more than one plant card within a dashboard tab. I only got one though so this likely is not the culprit.

**Comment by Olen** [comment]
I'm closing this as it has nothing to do with this plant integration
