### ISSUE TITLE
When adding a new plant, it does not find it in OpenPlantBook. Help me please!

### ISSUE THREAD

**Issue by VikeDragon** [Olen/homeassistant-plant#97]
Greetings!
When adding a new plant, it does not find it in OpenPlantBook. I tried alocasia cucullata. I tried alocasia. I tried Capsicum from the example.
On the limits page, he writes that he has not found and there is no flag to return to the previous page.
Installed:
https://github.com/Olen/homeassistant-plant
https://github.com/Olen/lovelace-flower-card
https://github.com/Olen/home-assistant-openplantbook
OpenPlantBook is registered on the website.
I tried it through the Open PlantBook service.Search - finds everything.
Tried UI cards from here:
https://github.com/Olen/home-assistant-openplantbook/blob/main/examples/GUI.md
he finds everything in her.
On the website
https://open.plantbook.io/ui/plant-details/alocasia%20cucullata /
also finds without problems.
Why does it not find it from the integration when adding it?
Please help in solving the problem.

**Comment by Olen** [comment]
Please enable debugging of the integration and look at the logs.

**Comment by VikeDragon** [comment]
Greetings!
I turned on debug and got the following logs :
[log.log](https://github.com/Olen/homeassistant-plant/files/12467692/log.log)

**Comment by Olen** [comment]
You probably need to upgrade to a newer version of HA.

**Comment by VikeDragon** [comment]
I have the latest version of all components
![HA version](https://github.com/Olen/homeassistant-plant/assets/44431640/f16083ab-62f1-4a67-b2b6-8adc11de3b1f)

**Comment by Olen** [comment]
Please try the latest beta release, it should give a better error message, and possibly also solve the problem.

**Comment by Olen** [comment]
Released a new version, and hope it will fix this problem and a few others at the same time

**Comment by VikeDragon** [comment]
> Released a new version, and hope it will fix this problem and a few others at the same time

Greetings!

Yes, that's right, after the HA update everything started working fine. 
I already have 67 plant cards and how can I link them to OpenPlantBook now so that the limits are tightened from the OpenPlantBook site?

**Comment by Olen** [comment]
You need to go to Settings -> Devices -> Plant Monitor, and "Configure" each plant.
Make sure you have typed the species right, and check the "Force refresh data..." checkbox under "Options"

![image](https://github.com/Olen/homeassistant-plant/assets/203184/9cf721bb-a872-4d9f-abda-b1f1cb6679e9)

**Comment by VikeDragon** [comment]
Thank you for your support and cool development!
