### ISSUE TITLE
Update for plants fails

### ISSUE THREAD

**Issue by unreal2k15** [Olen/homeassistant-plant#99]
I was wondering if anyone can shed some light into the following Home assistant core log error. 

Any help would be much appreciated.

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/plant/__init__.py:651
Integration: Plant monitor (documentation, issues)
First occurred: September 3, 2023 at 12:39:09 (19980 occurrences)
Last logged: 09:27:44

Update for plant.dragon_tree fails
Update for plant.arrowhead fails
Update for plant.money_tree fails
Update for plant.dracaena_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/__init__.py", line 651, in update
    ).state
      ^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by Olen** [comment]
Looks like a problem with some of your sensors.  Try to add/remove/replace the source-sensors using the "replace_sensor()" service-call.

**Comment by unreal2k15** [comment]
Gotcha, i will give it a go and monitor. Thank you.

**Comment by unreal2k15** [comment]
@Olen confirmed everything seems to work great now after removing all sensors with "replace_sensor()" and re-adding the sensors. Thank you for the advice and great work.
